//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteT1.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewUser", Namespace="http://schemas.datacontract.org/2004/07/DatabaseServices")]
    [System.SerializableAttribute()]
    public partial class NewUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime bdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bdate {
            get {
                return this.bdateField;
            }
            set {
                if ((this.bdateField.Equals(value) != true)) {
                    this.bdateField = value;
                    this.RaisePropertyChanged("bdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fn {
            get {
                return this.fnField;
            }
            set {
                if ((object.ReferenceEquals(this.fnField, value) != true)) {
                    this.fnField = value;
                    this.RaisePropertyChanged("fn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imgURL {
            get {
                return this.imgURLField;
            }
            set {
                if ((object.ReferenceEquals(this.imgURLField, value) != true)) {
                    this.imgURLField = value;
                    this.RaisePropertyChanged("imgURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ln {
            get {
                return this.lnField;
            }
            set {
                if ((object.ReferenceEquals(this.lnField, value) != true)) {
                    this.lnField = value;
                    this.RaisePropertyChanged("ln");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr {
            get {
                return this.usrField;
            }
            set {
                if ((object.ReferenceEquals(this.usrField, value) != true)) {
                    this.usrField = value;
                    this.RaisePropertyChanged("usr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertNewUser", ReplyAction="http://tempuri.org/IUserService/InsertNewUserResponse")]
        bool InsertNewUser(WebsiteT1.UserServiceReference.NewUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertNewUser", ReplyAction="http://tempuri.org/IUserService/InsertNewUserResponse")]
        System.Threading.Tasks.Task<bool> InsertNewUserAsync(WebsiteT1.UserServiceReference.NewUser newUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : WebsiteT1.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WebsiteT1.UserServiceReference.IUserService>, WebsiteT1.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertNewUser(WebsiteT1.UserServiceReference.NewUser newUser) {
            return base.Channel.InsertNewUser(newUser);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNewUserAsync(WebsiteT1.UserServiceReference.NewUser newUser) {
            return base.Channel.InsertNewUserAsync(newUser);
        }
    }
}
